on:
  push:
    branches: [main]

jobs:
  generate-wasm-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --target wasm32-unknown-unknown
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-build
          path: target/wasm32-unknown-unknown/debug/soft_body_simulation.wasm
